# You can freely (re)use this BitBucket template to enable CI (Continuous Integration) for your own open font project.
# Your project needs to make use of smith. See https://github.com/silnrsi/smith
# You may need to adjust some variables.
# For documentation on the recommended steps see Font Development Best Practises at http://silnrsi.github.io/FDBP
# More details in the BitBucket documentation at https://bitbucket.org/product/features/pipelines
# Enjoy and let us know if you find issues.


image: ubuntu:xenial

pipelines:
  default:
    - step:
      name: installing toolchain
        script:
          - apt-get install -y software-properties-common
          - add-apt-repository -y ppa:silnrsi/smith
          - sudo add-apt-repository -y ppa:jonathonf/texlive-2018
          - apt update -q -y
          - apt install smith-font -y --no-install-recommends

    - step:
      name: running smith targets
        script:
          - smith configure
          - smith build
          - smith alltests
          - smith fontlint
          - smith zip
          - smith tarball
          - smith release
        artifacts:
          - results/releases/*
          - results/*.html
          - results/*.pdf
          - results/*.txt
          - results/*err*
          - results/tests/*
