# You can freely (re)use this GitLab template to enable CI (Continuous Integration) for your own open font project.
# Your project needs to make use of smith. See https://github.com/silnrsi/smith
# For documentation on the recommended steps see Font Development Best Practises at http://silnrsi.github.io/FDBP
# More details in the GitLab documentation at https://docs.gitlab.com/ce/ci/README.html
# Enjoy and let us know if you find issues. 

image: "ubuntu:xenial"

build:
  stage: build
  before_script:
    - apt-get update -q -y
    - apt-get install -q -y software-properties-common libterm-readline-gnu-perl
    - add-apt-repository -y ppa:silnrsi/smith
    - add-apt-repository -y ppa:fontforge/fontforge
    - add-apt-repository -y ppa:jonathonf/texlive-2018
    - add-apt-repository -y ppa:git-core/ppa
    - apt-get update -q -y 
    - apt-get install sile python-odf python-odf-tools libjson-perl libtext-csv-perl libharfbuzz-bin -y
    - apt-get install smith-font -y --no-install-recommends

  script:
    - smith configure
    - smith build
    - smith alltests
    - smith pyfontaine
    - smith fontlint
    - smith zip
    - smith tarball
    - smith release 

  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}${CI_COMMIT_SHA:0:8}-build${CI_JOB_ID}"
    paths:
    - results/releases/*
    - results/*.html
    - results/*.pdf
    - results/*.txt
    - results/*err*
    - results/tests/*
