# You can freely (re)use this gitlab template to enable CI (Continuous Integration) for your own project.
# Your projects needs to make use of smith. See https://github.com/silnrsi/smith
# Documentation on the steps needed to use this will be available soon at http://silnrsi.github.io/FDBP
# More details on the gitlab documentation: https://docs.gitlab.com/ce/ci/README.html

image: "ubuntu:18.04"

build:
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -q -y
    - apt-get install -q -y software-properties-common 
    - add-apt-repository -y ppa:silnrsi/smith-py3
    #- add-apt-repository -y ppa:fontforge/fontforge
    - add-apt-repository -y ppa:jonathonf/texlive-2019
    - add-apt-repository -y ppa:git-core/ppa
    - add-apt-repository -y ppa:sile-typesetter/sile
    - apt-get update -y 
    - apt-get install smith-font -y --no-install-recommends


  script:
    - smith configure
    - smith build
    - smith alltests
    - smith zip
    - smith tarball
    - smith release

  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}${CI_COMMIT_SHA:0:8}-build${CI_JOB_ID}"
    paths:
    - results/releases/*
    - results/*.html
    - results/*.pdf
    - results/*.txt
    - results/*err*
    - results/tests/*
