# You can freely (re)use this GitHub action template to enable CI (Continuous Integration) for your own open font project.
# Your project needs to make use of smith. See https://github.com/silnrsi/smith
# You may need to adjust some variables.
# For documentation on the recommended steps see Font Development Best Practises at http://silnrsi.github.io/FDBP
# and the SIL Font Development Notes at https://silnrsi.github.io/silfontdev
# More details in the GitHub Action documentation at https://help.github.com/en/articles/about-github-actions
# Enjoy and let us know if you find issues.

---
name: smith

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Install smith toolchain
        run: |
          sudo add-apt-repository -y ppa:silnrsi/smith-py3
          sudo add-apt-repository -y ppa:fontforge/fontforge
          sudo add-apt-repository -y ppa:jonathonf/texlive-2019
          sudo add-apt-repository -y ppa:git-core/ppa
          sudo apt-get update -q -y
          sudo apt-get remove *php* *mono* *dotnet* -y
          sudo apt-get autoremove -y
          sudo apt-get upgrade -q -y
          sudo apt-get install libjson-perl libtext-csv-perl libharfbuzz-bin -y
          sudo apt-get install smith-font -y --no-install-recommends
          sudo apt-get install python3-pip python3-setuptools -y
          sudo pip3 install --upgrade git+https://github.com/googlefonts/fontbakery.git@master#egg=fontbakery
      - name: configure / build / test / release
        run: |
          smith version
          smith configure
          smith build
          smith alltests
          smith zip
          smith tarball
          smith release
      - uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: results/releases
